[programs.localnet]
gem_bank = "niieYBwuo5ECxmy1iCv2fwGNkEdbbn87LekDbaCt1fZ"
gem_farm = "9t5fVc99hmFP3k3gKd2NaBE6kxUuRLxwCssBxvoCXHMg"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/Users/madbook/guntXfLJzkewRM7eyvLSBQhRhiNGoGYZxybkDubF7uK.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

#[test]
#startup_wait = 100000

[[test.genesis]]
address = "metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s"
program = "./tests/programs/metaplex_token_metadata.so"